name = "kayal-onam26"
pages_build_output_dir = "out"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "kayal-onam26-db"
database_id = "8b59420b-5a89-4b14-994b-90127b65caf5"
