INSERT INTO categories (id, name, blurb, sort) VALUES ('starters', 'Starters', 'Light bites and shareable plates to open the meal.', 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('veg-samosa', 'starters', 'Veg Samosa (2 pcs)', 'Flaky and tender fried samosa, one of the most popular recipes in North Indian cuisine.', 990, '["veg"]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('paneer-pakora', 'starters', 'Paneer Pakora (2 pcs)', 'A popular evening snack made by batter frying Indian cottage cheese.', 1290, '["veg"]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('onion-bhaji', 'starters', 'Onion Bhaji (2 pcs)', 'Finely sliced onion in a fragrantly spiced batter, fried to crispy perfection.', 990, '["veg"]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('veg-basket', 'starters', 'Veg Basket', 'Grated fried potato baskets filled with chickpeas, potatoes, chutneys, curd, and chaat masala.', 1490, '["veg"]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('pappdi-chat', 'starters', 'Pappdi Chat', 'Crunchy poori base topped with lip-smacking chutneys.', 1490, '["veg","signature"]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('gobi-manchuriyan', 'starters', 'Gobi Manchuriyan', 'Crisp fried cauliflower tossed in slightly sour, sweet, and hot sauces.', 1590, '["veg","spicy"]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('paneer-chilly', 'starters', 'Paneer Chilly', 'Fried paneer tossed in sweet, sour, and spicy chilli sauce.', 1990, '["veg","spicy"]', 1, 0, 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('hara-bara-kebab', 'starters', 'Hara Bara Kebab', 'Spiced patties made with spinach, green peas, and potatoes.', 990, '["veg"]', 1, 0, 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('tandoori-chicken-half', 'starters', 'Tandoori Chicken Half', 'Smoky chicken appetiser cooked in the tandoor.', 1890, '["signature"]', 1, 0, 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('tandoori-chicken-full', 'starters', 'Tandoori Chicken Full', 'Smoky chicken appetiser cooked in the tandoor.', 2490, '[]', 1, 0, 9);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chicken-tikka', 'starters', 'Chicken Tikka (4 pcs)', 'Small pieces of marinated chicken threaded onto skewers.', 1490, '["spicy"]', 1, 0, 10);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('malai-tikka', 'starters', 'Malai Tikka (4 pcs)', 'Tender and juicy Murgh Malai Tikka, bursting with flavour.', 1490, '[]', 1, 0, 11);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('lamb-chops', 'starters', 'Lamb Chops (4 pcs)', 'Lamb chops marinated for hours and cooked on tawa or in the oven.', 3490, '[]', 1, 0, 12);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('sheek-kabab', 'starters', 'Sheek Kabab (4 pcs)', 'Spiced ground lamb threaded onto skewers and grilled until charred.', 2290, '[]', 1, 0, 13);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('mix-non-veg-platter', 'starters', 'Mix Non-Veg Platter (2 pcs each)', 'Assorted tikkas, tandoor, and grills.', 3690, '["spicy"]', 1, 0, 14);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('tiger-prawns', 'starters', 'Tiger Prawns (6 pcs)', 'Marinated and grilled Indian tandoori shrimp skewers.', 2490, '["signature"]', 1, 0, 15);
INSERT INTO categories (id, name, blurb, sort) VALUES ('vegetarian', 'Main Course Vegetarian', 'Wholesome vegetable curries, lentils and paneer from the Kerala coast.', 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('dal-tadka', 'vegetarian', 'Daal Tadka', 'Lentils tempered with cumin seed, garlic, and butter.', 1690, '["veg"]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('daal-makhani', 'vegetarian', 'Daal Makhani', 'Lentils soaked overnight and simmered with herbs and spices.', 1690, '["veg"]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('navratan-korma', 'vegetarian', 'Navratan Korma', 'Mixed vegetables and fruit in a rich curry sauce.', 1990, '["veg"]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('aloo-gobi', 'vegetarian', 'Aloo Gobi', 'Cauliflower and potatoes cooked in a rich curry sauce.', 1990, '["veg"]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('shahi-baingan', 'vegetarian', 'Shahi Baingan', 'Eggplant cooked in exotic sauce, finished with fennel, fresh coriander, and cream.', 1990, '["veg"]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('malai-kofta', 'vegetarian', 'Malai Kofta', 'Potato and cottage cheese dumplings in a cashew sauce.', 1990, '["veg"]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('paneer-tikka-masala', 'vegetarian', 'Paneer Tikka Masala', 'Paneer marinated and finished in a semi-dry sauce with coriander.', 1990, '["veg"]', 1, 0, 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('shaai-paneer', 'vegetarian', 'Shaai Paneer', 'Home-made cheese cooked in exotic sauce finished with fennel and fresh coriander.', 1990, '["veg"]', 1, 0, 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('butter-paneer-masala', 'vegetarian', 'Butter Paneer Masala', 'Cottage cheese in a rich tomato cashew gravy.', 1990, '["veg"]', 1, 0, 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('palak-paneer', 'vegetarian', 'Palak Paneer', 'Cottage cheese cooked with spinach and spices.', 1990, '["veg"]', 1, 0, 9);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('kadai-paneer', 'vegetarian', 'Kadai Paneer', 'Cottage cheese cooked with wok-fried spices, onion, and tomato.', 1990, '["veg"]', 1, 0, 10);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chakka', 'vegetarian', 'Chakka', 'Kerala style jackfruit dish.', 1495, '["veg"]', 1, 0, 11);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('masala-mash-potato', 'vegetarian', 'Masala Mash Potato', 'Mash potato prepared in Kerala recipe.', 995, '["veg"]', 1, 0, 12);
INSERT INTO categories (id, name, blurb, sort) VALUES ('chicken-meat', 'Main Course Poultry', 'Woodfire curries, roasts and ularthiyathu from the village repertoire.', 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('butter-chicken', 'chicken-meat', 'Butter Chicken', 'Marinated chicken fillets cooked in tandoor, sauteed in butter tomato sauce.', 2390, '[]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chicken-korma', 'chicken-meat', 'Chicken Korma', 'Chicken simmered in freshly ground coconut, cashew nut paste, and exotic spice.', 2390, '[]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chicken-vindaloo', 'chicken-meat', 'Chicken Vindaloo', 'A very popular spicy dish from Goa.', 2390, '["spicy"]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('mango-chicken', 'chicken-meat', 'Mango Chicken', 'Chicken fillets cooked in a delicious mango gravy.', 2390, '[]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('kadai-chicken', 'chicken-meat', 'Kadai Chicken', 'Thigh fillets marinated in yoghurt, wok fried with spices, tomatoes, onion, and capsicum.', 2390, '[]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('madras-chicken', 'chicken-meat', 'Madras Chicken', 'Chicken cooked with fried coconut and red spices.', 2390, '[]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chicken-chettinad', 'chicken-meat', 'Chicken Chettinadu', 'Boneless chicken in authentic South Indian style with black pepper, onion, and tomatoes.', 2390, '["spicy"]', 1, 0, 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chicken-tikka-masala', 'chicken-meat', 'Chicken Tikka Masala', 'Grilled chicken sauteed with onion, capsicum, tomato, spices, and fenugreek leaves.', 2390, '[]', 1, 0, 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chilly-chicken', 'chicken-meat', 'Chilly Chicken', 'Strips of marinated chicken sauteed with onions and capsicum.', 2390, '["spicy"]', 1, 0, 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('kizhi-porotta', 'chicken-meat', 'Kizhi Porotta', 'Kizhi Porotta (Chicken / Beef/Veg) — traditional Kerala bundle: porotta stuffed with curry meat, wrapped and steamed in banana leaf.', 2500, '["signature"]', 1, 0, 9);
INSERT INTO categories (id, name, blurb, sort) VALUES ('main-course-meat', 'Main Course Meat', 'Hearty meat dishes prepared with authentic spices, slow-cooked or roasted for rich, traditional flavour.', 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201277867', 'main-course-meat', 'Lamb Rogan Josh', 'All-time favourite with tomatoes and a blend of spices.', 2595, '[]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201414189', 'main-course-meat', 'Lamb Korma', 'Lamb simmered with freshly ground coconut, cashew nut paste, and exotic spices.', 2595, '[]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201489398', 'main-course-meat', 'Lamb Pepper Masala', 'Diced lamb in country style with fresh herbs and peppercorn.', 2595, '[]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201462904', 'main-course-meat', 'Lamb Saagwala', 'Tender goat cooked on the bone in the chef''s secret recipe.', 2595, '[]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201573954', 'main-course-meat', 'Goat Curry', 'Roasted coconut sauce with whole spices blended with coconut.', 2595, '[]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201578020', 'main-course-meat', 'Cochin Beef', 'Home-style stew from Cochin — tender beef cooked with special roasted masala.', 2595, '[]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201674138', 'main-course-meat', 'Beef Curry', 'Traditional beef curry with shallots and Kerala garam masala.', 2595, '[]', 1, 0, 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201714731', 'main-course-meat', 'Beef Niligiri', 'Popular South Indian beef curry cooked with green masala.', 2595, '[]', 1, 0, 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201730713', 'main-course-meat', 'Beef Korma', 'Beef seared and simmered in a broth with spices and coconut milk.', 2595, '[]', 1, 0, 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787201790499', 'main-course-meat', 'Beef Ulathiyathu', 'Chef''s special with meat masala and spices.', 2595, '[]', 1, 0, 9);
INSERT INTO categories (id, name, blurb, sort) VALUES ('seafood', 'Main Course - From The Ocean', 'Fish and prawns from the backwater — bold spice, coconut, and banana leaf.', 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('goan-fish-curry', 'seafood', 'Goan Fish Curry', 'Fish curry with coconut from the beaches of Goa.', 2490, '[]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('madras-fish-curry', 'seafood', 'Madras Fish Curry', 'Fish cooked with fenugreek, green chillies, and tamarind.', 2490, '["spicy"]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('fish-mollie', 'seafood', 'Fish Mollie', 'Kerala style fish curry cooked in a coconut milk-based gravy.', 2490, '[]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('kerala-fish-curry', 'seafood', 'Kerala Fish Curry', 'Kerala style fish curry.', 2490, '["signature"]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('prawn-masala', 'seafood', 'Prawn Masala', 'Prawns cooked in thick gravy with tomatoes, green chillies, capsicum, and coriander.', 2690, '["spicy"]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('malabar-prawn-curry', 'seafood', 'Malabar Prawn Curry', 'King prawns simmered in coconut gravy with tamarind spices.', 2690, '[]', 1, 0, 5);
INSERT INTO categories (id, name, blurb, sort) VALUES ('rice', 'Rice & Breads', 'Fragrant basmati and Kerala rice dishes, layered and slow-cooked.', 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('rice', 'rice', 'Rice', 'Steamed rice, served with so many things.', 695, '["veg"]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('saffron-rice', 'rice', 'Saffron Rice', 'Aromatic rice with saffron.', 995, '["veg"]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('matta-rice', 'rice', 'Matta Rice', 'Special Kerala matta rice.', 1295, '["veg"]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('kashmir-veg-pulao', 'rice', 'Kashmir / Veg Pulao', 'Long basmati rice cooked with fruits and green peas, served with fried onions and coriander.', 1495, '["veg"]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('fried-rice', 'rice', 'Fried Rice — Veg / Non-Veg', 'Basmati rice sauteed with soy sauce and spring vegetables.', 1995, '[]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('veg-biriyani', 'rice', 'Veg Biriyani', 'Rice dish with vegetables.', 1995, '["veg"]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('biriyani-chicken', 'rice', 'Biriyani — Chicken', 'Kerala specialty. Basmati rice simmered with chicken, chef''s special herbs and spices, finished with saffron and cardamom.', 2195, '[]', 1, 0, 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('biriyani-lamb-goat', 'rice', 'Biriyani — Lamb / Goat', 'Kerala specialty. Basmati rice simmered with lamb or goat, chef''s special herbs and spices, finished with saffron and cardamom.', 2395, '[]', 1, 0, 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('prawn-biriyani', 'rice', 'Prawn Biriyani', 'Chef''s special dum biriyani.', 2495, '["signature"]', 1, 0, 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205013734', 'rice', 'Roti', 'Wholemeal Indian bread cooked in the tandoori oven.', 395, '[]', 1, 0, 9);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205031767', 'rice', 'Naan', 'Indian bread made with all-purpose flour.', 395, '[]', 1, 0, 10);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205059544', 'rice', 'Butter Naan / Garlic Naan', 'All-purpose flour naan tossed with butter and garlic.', 495, '[]', 1, 0, 11);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205079856', 'rice', 'Cheese Naan', 'All-purpose flour naan stuffed with cheese.', 595, '[]', 1, 0, 12);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205091257', 'rice', 'Garlic Cheese Naan', 'All-purpose flour naan stuffed with cheese and Garlic.', 595, '[]', 1, 0, 13);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205166982', 'rice', 'Kashmiri Naan', 'Naan with fruits, nuts, raisins, and cottage cheese.', 595, '[]', 1, 0, 14);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205184327', 'rice', 'Aloo Paratha', 'Wholewheat stuffed with spicy potato filling, served hot with yogurt and pickles.', 595, '["signature"]', 1, 0, 15);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('thalassery-biryani', 'rice', 'Sultan Biriyani in Kaima Rice (Chicken/ Goat)', 'Short-grain rice layered with spiced meat, fried onion and ghee.', 2195, '["signature"]', 1, 0, 16);
INSERT INTO categories (id, name, blurb, sort) VALUES ('specials', 'Specials', 'All the below items are as per availability', 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('thattukada-chicken-fry', 'specials', 'Thattukada Chicken Fry', 'Crispy, spicy chicken fry tossed with aromatic South Indian spices, just like a classic thattukada favourite', 1995, '["signature","spicy"]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787198056617', 'specials', 'Kattupothu (Buffalo) Ularthiyathu', 'Slow-cooked buffalo meat stir-fried with aromatic spices, curry leaves and roasted coconut for a rich, authentic Kerala-style flavour.', 2500, '["spicy","signature"]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787198214241', 'specials', 'Maan (Deer) Ularthiyathu', 'Tender deer meat slow-cooked and stir-fried with aromatic Kerala spices, curry leaves and roasted coconut for a rich, rustic flavour.', 2995, '[]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787198304197', 'specials', 'Muyal (Rabbit) Piralan', 'Tender rabbit meat cooked and stir-fried with aromatic Kerala spices, onions and curry leaves for a deliciously rustic, traditional flavour.', 2995, '[]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787198376885', 'specials', 'Panni Ularthiyathu', 'Pork slow-cooked and stir-fried with aromatic Kerala spices, curry leaves and roasted coconut for a rich, spicy and authentic flavour.', 2295, '[]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787202115273', 'specials', 'Duck Curry/Roast', 'Kerala style duck roast simmered in an aromatic spicy masala.', 2595, '[]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787202148137', 'specials', 'Beef Roast', 'Kerala style beef roast simmered in an aromatic spicy masala.', 2695, '[]', 1, 0, 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787202798205', 'specials', 'Nadan Chicken Curry', 'Special Kerala masala.', 2295, '[]', 1, 0, 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787202854835', 'specials', 'Buffallo Curry', 'Kerala style buffalo dish.', 2595, '[]', 1, 0, 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787202886613', 'specials', 'Chilly Beef', 'Crispy strips of beef in a tangy spicy sauce.', 2595, '[]', 1, 0, 9);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787204497589', 'specials', 'Porotta', 'Flaky, layered Kerala-style flatbread, hand-stretched and cooked to golden perfection. Soft inside, crisp and flaky outside.', 495, '[]', 1, 0, 10);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787204558328', 'specials', 'chakka puzhukku', 'Tender jackfruit boiled to perfection, lightly seasoned for a simple, wholesome and authentic Kerala-style taste.', 1495, '[]', 1, 0, 11);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787204225074', 'specials', ' kappa vevichathu', 'Kerala style tapioca dish.', 1295, '[]', 1, 0, 12);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787204652122', 'specials', 'Appam', 'Fermented rice batters from the griddle and steamer.', 300, '[]', 1, 0, 13);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787204778612', 'specials', 'Masala Mash Potato', NULL, 995, '[]', 1, 0, 14);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('pothichoru', 'specials', 'Pothichoru ( Lunch Only )', 'A traditional Kerala packed lunch wrapped in a banana leaf, featuring steamed rice, flavorful curries, vegetable sides, pickle, papad, and other homestyle accompaniments. The leaf wrapping allows the flavors to blend beautifully, creating an authentic and comforting Kerala meal.', 2500, '["signature"]', 1, 0, 15);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('kappa-biryani', 'specials', 'Kappa Biryani', 'A flavorful Kerala dish combining tender tapioca with spiced meat and aromatic herbs.', 2495, '["spicy","signature"]', 1, 0, 16);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('chatti-choru', 'specials', 'Chattichoru ( Lunch Only )', 'A traditional Kerala-style rice meal served in a clay pot with flavorful curries and homestyle accompaniments.', 2995, '["signature"]', 1, 0, 17);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787304856679', 'specials', 'Nadan Oonu ( Lunch Only )', 'A traditional Kerala style lunch served featuring Matta rice with curries, sides and seasonal accompaniments.', 2500, '["signature"]', 1, 0, 18);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787304992593', 'specials', 'Kizhi Porotta ( Chicken/Beef/Veg)', 'Flaky porotta wrapped in a banana leaf with flavorful meat curry and spices, then steamed to perfection.', 2500, '["signature"]', 1, 0, 19);
INSERT INTO categories (id, name, blurb, sort) VALUES ('seafood-specials', 'Seafood Specials', 'Fish and prawns from the backwater — bold spice, coconut, and banana leaf.', 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787203306987', 'seafood-specials', 'Crab Roast', NULL, 2995, '[]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787203412429', 'seafood-specials', 'Chemeen Roast', 'Prawns in red chilli and tamarind-based red curry sauce.', 2995, '[]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787203463346', 'seafood-specials', 'Mussels Varatty (Kallummakai, 10 pcs)', 'Stir fried mussels in authentic spices.', 1995, '[]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787203488867', 'seafood-specials', 'Kakkayirachi (Clams)', 'Stir fried clams with authentic Kerala spices.', 1995, '[]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787203510890', 'seafood-specials', 'Pan Fried Fish', 'Fish fried with Kerala spices.', 3000, '[]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('meen-pollichathu', 'seafood-specials', 'Meen Pollichathu', 'Signature dish — fish wrapped in banana leaf, giving a unique flavour.', 4000, '[]', 1, 0, 5);
INSERT INTO categories (id, name, blurb, sort) VALUES ('sides-pickles', 'Sides', 'Papadam, salads and the sharp bite of pickle.', 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('pappadam', 'sides-pickles', 'Papadam/ Pickle (Each)', 'Traditional South Indian pappadam.', 395, '["veg"]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('green-salad', 'sides-pickles', 'Green Salad', 'Fresh vegetable salad.', 795, '["veg"]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205716333', 'sides-pickles', 'Onion Slice', 'Freshly sliced onions, crisp and mildly sweet, served as a refreshing accompaniment to your meal.
', 395, '[]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205744328', 'sides-pickles', 'Mint Sauce', 'Refreshing mint sauce made with fresh mint, herbs and a hint of spice, perfect as a cool accompaniment to your meal.
', 395, '[]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205762650', 'sides-pickles', 'Raita', 'Creamy yogurt mixed with fresh cucumber, herbs and mild spices for a cool, refreshing accompaniment.
', 395, '[]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205775366', 'sides-pickles', 'Gulab Jamun', 'Soft, melt-in-the-mouth milk dumplings soaked in fragrant sugar syrup, served warm for a classic Indian sweet treat.
', 695, '[]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205798205', 'sides-pickles', 'Ice cream(2 Scoops)', 'Two scoops of creamy, delicious ice cream, served chilled for a simple and satisfying sweet treat.
', 995, '[]', 1, 0, 6);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205824149', 'sides-pickles', 'Fruit Salad', 'Fresh seasonal fruits, chilled and tossed together for a naturally sweet, juicy and refreshing dessert.
', 995, '[]', 1, 0, 7);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205839633', 'sides-pickles', 'Fruit Salad with Ice Cream', 'Fresh seasonal fruits served chilled with creamy vanilla ice cream for a refreshing and indulgent dessert.', 1495, '[]', 1, 0, 8);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787205871631', 'sides-pickles', 'Falooda', 'Classic Indian falooda layered with silky vermicelli, basil seeds, creamy milk and sweet, refreshing flavours, topped with ice cream.', 1495, '[]', 1, 0, 9);
INSERT INTO categories (id, name, blurb, sort) VALUES ('desserts-drinks', 'Drinks & Beverages', 'Sweet finishes and refreshing pours.', 9);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('mango-lassi', 'desserts-drinks', 'Lassi — Mango / Salt / Sweet', 'Yogurt-based drink blended with water, spices, dry fruits, or fruit.', 695, '["veg"]', 1, 0, 0);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('new-item-1787206200698', 'desserts-drinks', 'Mineral Water', NULL, 395, '[]', 1, 0, 1);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('coke', 'desserts-drinks', 'Soft Drinks', NULL, 395, '["veg"]', 1, 0, 2);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('orange-juice', 'desserts-drinks', 'Orange Juice', 'Fresh orange juice.', 1295, '["veg"]', 1, 0, 3);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('watermelon-juice', 'desserts-drinks', 'Watermelon Juice', 'Fresh watermelon juice.', 1295, '["veg"]', 1, 0, 4);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('lemon-lime-bitter', 'desserts-drinks', 'Fresh Lime Juice', 'Lemonade, lime cordial, and Angostura bitters.', 999, '["veg"]', 1, 0, 5);
INSERT INTO menu_items (id, category_id, name, description, price_cents, tags_json, available, listed, sort) VALUES ('pineapple-juice', 'desserts-drinks', 'Fresh Lime Soda', 'Fresh juice.', 1199, '["veg"]', 1, 0, 6);
INSERT INTO categories (id, name, blurb, sort) VALUES ('custom', 'Custom', NULL, 10);
INSERT INTO zones (id, name, areas, fee_cents, free_over_cents, eta_minutes, active, sort) VALUES
  ('zone-quakers-hill', 'Quakers Hill 2763', 'Quakers Hill NSW 2763', 1000, 6000, NULL, 1, 0),
  ('zone-marsden-park', 'Marsden Park 2765', 'Marsden Park NSW 2765', 1000, 6000, NULL, 1, 1),
  ('zone-riverstone', 'Riverstone 2765', 'Riverstone NSW 2765', 1000, 6000, NULL, 1, 2),
  ('zone-schofields', 'Schofields 2762', 'Schofields NSW 2762', 1000, 6000, NULL, 1, 3),
  ('zone-the-ponds', 'The Ponds 2769', 'The Ponds NSW 2769', 1000, 6000, NULL, 1, 4),
  ('zone-tallawong', 'Tallawong 2762', 'Tallawong NSW 2762', 1000, 6000, NULL, 1, 5),
  ('zone-rouse-hill', 'Rouse Hill 2155', 'Rouse Hill NSW 2155', 1000, 6000, NULL, 1, 6),
  ('zone-kellyville-ridge', 'Kellyville Ridge 2155', 'Kellyville Ridge NSW 2155', 1000, 6000, NULL, 1, 7);


-- Placeholder payment details: set the real ones in dashboard → Settings.
INSERT INTO settings (key, value_json) VALUES
  ('restaurant', '{"name":"Kayal Foods","phone":"","email":"hello@kayal.com.au"}'),
  ('payment', '{"instructions":"Pay by bank transfer, then upload your receipt or enter the transaction reference on your order page.","bank":{"accountName":"REPLACE","bsb":"REPLACE","accountNumber":"REPLACE"},"payid":""}'),
  ('tax', '{"rateBps":1000,"inclusive":false}'),
  ('delivery', '{"pickupEnabled":true,"deliveryEnabled":true}');

